import findLadders from "../../../src/deepAndBreadthSearch/126_Word_Ladder_II/index1";

// test("1", () => {
//   expect(findLadders("hit", "cog", ["hot", "hib", "dot", "dog", "lot", "log", "cog"])).toEqual([
//     ["hit", "hot", "dot", "dog", "cog"],
//     ["hit", "hot", "lot", "log", "cog"],
//   ]);
// });

// test("2", () => {
//   expect(findLadders("a", "c", ["a", "b", "c"])).toEqual([["a", "c"]]);
// });
test("3", () => {
  expect(
    findLadders("magic", "pearl", [
      "flail",
      "halon",
      "lexus",
      "joint",
      "pears",
      "slabs",
      "lorie",
      "lapse",
      "wroth",
      "yalow",
      "swear",
      "cavil",
      "piety",
      "yogis",
      "dhaka",
      "laxer",
      "tatum",
      "provo",
      "truss",
      "tends",
      "deana",
      "dried",
      "hutch",
      "basho",
      "flyby",
      "miler",
      "fries",
      "floes",
      "lingo",
      "wider",
      "scary",
      "marks",
      "perry",
      "igloo",
      "melts",
      "lanny",
      "satan",
      "foamy",
      "perks",
      "denim",
      "plugs",
      "cloak",
      "cyril",
      "women",
      "issue",
      "rocky",
      "marry",
      "trash",
      "merry",
      "topic",
      "hicks",
      "dicky",
      "prado",
      "casio",
      "lapel",
      "diane",
      "serer",
      "paige",
      "parry",
      "elope",
      "balds",
      "dated",
      "copra",
      "earth",
      "marty",
      "slake",
      "balms",
      "daryl",
      "loves",
      "civet",
      "sweat",
      "daley",
      "touch",
      "maria",
      "dacca",
      "muggy",
      "chore",
      "felix",
      "ogled",
      "acids",
      "terse",
      "cults",
      "darla",
      "snubs",
      "boats",
      "recta",
      "cohan",
      "purse",
      "joist",
      "grosz",
      "sheri",
      "steam",
      "manic",
      "luisa",
      "gluts",
      "spits",
      "boxer",
      "abner",
      "cooke",
      "scowl",
      "kenya",
      "hasps",
      "roger",
      "edwin",
      "black",
      "terns",
      "folks",
      "demur",
      "dingo",
      "party",
      "brian",
      "numbs",
      "forgo",
      "gunny",
      "waled",
      "bucks",
      "titan",
      "ruffs",
      "pizza",
      "ravel",
      "poole",
      "suits",
      "stoic",
      "segre",
      "white",
      "lemur",
      "belts",
      "scums",
      "parks",
      "gusts",
      "ozark",
      "umped",
      "heard",
      "lorna",
      "emile",
      "orbit",
      "onset",
      "cruet",
      "amiss",
      "fumed",
      "gelds",
      "italy",
      "rakes",
      "loxed",
      "kilts",
      "mania",
      "tombs",
      "gaped",
      "merge",
      "molar",
      "smith",
      "tangs",
      "misty",
      "wefts",
      "yawns",
      "smile",
      "scuff",
      "width",
      "paris",
      "coded",
      "sodom",
      "shits",
      "benny",
      "pudgy",
      "mayer",
      "peary",
      "curve",
      "tulsa",
      "ramos",
      "thick",
      "dogie",
      "gourd",
      "strop",
      "ahmad",
      "clove",
      "tract",
      "calyx",
      "maris",
      "wants",
      "lipid",
      "pearl",
      "maybe",
      "banjo",
      "south",
      "blend",
      "diana",
      "lanai",
      "waged",
      "shari",
      "magic",
      "duchy",
      "decca",
      "wried",
      "maine",
      "nutty",
      "turns",
      "satyr",
      "holds",
      "finks",
      "twits",
      "peaks",
      "teems",
      "peace",
      "melon",
      "czars",
      "robby",
      "tabby",
      "shove",
      "minty",
      "marta",
      "dregs",
      "lacks",
      "casts",
      "aruba",
      "stall",
      "nurse",
      "jewry",
      "knuth",
    ])
  ).toEqual([]);
});

// test("2", () => {
//   expect(findLadders("hot", "dog", ["hot", "cog", "dog", "tot", "hog", "hop", "pot", "dot"])).toEqual([
//     ["hot", "hog", "dog"],
//     ["hot", "dot", "dog"],
//   ]);
// });
// test("3", () => {
//   expect(findLadders("hit", "cog", ["hot", "dot", "dog", "lot", "log"])).toEqual([]);
// });

// test("3", () => {
//   expect(
//     findLadders("qa", "sq", [
//       "si",
//       "go",
//       "se",
//       "cm",
//       "so",
//       "ph",
//       "mt",
//       "db",
//       "mb",
//       "sb",
//       "kr",
//       "ln",
//       "tm",
//       "le",
//       "av",
//       "sm",
//       "ar",
//       "ci",
//       "ca",
//       "br",
//       "ti",
//       "ba",
//       "to",
//       "ra",
//       "fa",
//       "yo",
//       "ow",
//       "sn",
//       "ya",
//       "cr",
//       "po",
//       "fe",
//       "ho",
//       "ma",
//       "re",
//       "or",
//       "rn",
//       "au",
//       "ur",
//       "rh",
//       "sr",
//       "tc",
//       "lt",
//       "lo",
//       "as",
//       "fr",
//       "nb",
//       "yb",
//       "if",
//       "pb",
//       "ge",
//       "th",
//       "pm",
//       "rb",
//       "sh",
//       "co",
//       "ga",
//       "li",
//       "ha",
//       "hz",
//       "no",
//       "bi",
//       "di",
//       "hi",
//       "qa",
//       "pi",
//       "os",
//       "uh",
//       "wm",
//       "an",
//       "me",
//       "mo",
//       "na",
//       "la",
//       "st",
//       "er",
//       "sc",
//       "ne",
//       "mn",
//       "mi",
//       "am",
//       "ex",
//       "pt",
//       "io",
//       "be",
//       "fm",
//       "ta",
//       "tb",
//       "ni",
//       "mr",
//       "pa",
//       "he",
//       "lr",
//       "sq",
//       "ye",
//     ])
//   ).toEqual([
//     ["hot", "hog", "dog"],
//     ["hot", "dot", "dog"],
//   ]);
// });
