import ladderLength from "../../../src/search/126_Word_Ladder_II/index";

test("1", () => {
  expect(ladderLength("hit", "cog", ["hot", "dot", "dog", "lot", "log", "cog"])).toEqual([
    ["hit", "hot", "dot", "dog", "cog"],
    ["hit", "hot", "lot", "log", "cog"],
  ]);
});

// test("2", () => {
//   expect(ladderLength("hit", "cog", ["hot", "dot", "dog", "lot", "log"])).toEqual([]);
// });
// test("3", () => {
//   expect(
//     ladderLength("qa", "sq", [
//       "si",
//       "go",
//       "se",
//       "cm",
//       "so",
//       "ph",
//       "mt",
//       "db",
//       "mb",
//       "sb",
//       "kr",
//       "ln",
//       "tm",
//       "le",
//       "av",
//       "sm",
//       "ar",
//       "ci",
//       "ca",
//       "br",
//       "ti",
//       "ba",
//       "to",
//       "ra",
//       "fa",
//       "yo",
//       "ow",
//       "sn",
//       "ya",
//       "cr",
//       "po",
//       "fe",
//       "ho",
//       "ma",
//       "re",
//       "or",
//       "rn",
//       "au",
//       "ur",
//       "rh",
//       "sr",
//       "tc",
//       "lt",
//       "lo",
//       "as",
//       "fr",
//       "nb",
//       "yb",
//       "if",
//       "pb",
//       "ge",
//       "th",
//       "pm",
//       "rb",
//       "sh",
//       "co",
//       "ga",
//       "li",
//       "ha",
//       "hz",
//       "no",
//       "bi",
//       "di",
//       "hi",
//       "qa",
//       "pi",
//       "os",
//       "uh",
//       "wm",
//       "an",
//       "me",
//       "mo",
//       "na",
//       "la",
//       "st",
//       "er",
//       "sc",
//       "ne",
//       "mn",
//       "mi",
//       "am",
//       "ex",
//       "pt",
//       "io",
//       "be",
//       "fm",
//       "ta",
//       "tb",
//       "ni",
//       "mr",
//       "pa",
//       "he",
//       "lr",
//       "sq",
//       "ye",
//     ])
//   ).toEqual([]);
// });
